# Generated by Django 4.2.5 on 2023-11-07 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product1',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
