# Generated by Django 4.2.5 on 2023-10-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscategory',
            name='image',
            field=models.ImageField(default=1, upload_to='subcategory'),
            preserve_default=False,
        ),
    ]
