# Generated by Django 4.2.5 on 2023-11-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating_f',
            new_name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='review_title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
