# Generated by Django 4.2.5 on 2023-10-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='products_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='p_tag', to='products.product_tag'),
        ),
    ]
