# Generated by Django 4.2.5 on 2023-11-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product1_image_productimage_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avilablesize',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
