# Generated by Django 4.2.5 on 2023-10-30 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_product_avilablesize_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avilablesize',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.size'),
        ),
        migrations.CreateModel(
            name='AvilableAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.FloatField()),
                ('original_price', models.FloatField(blank=True, null=True)),
                ('opening_stock', models.IntegerField()),
                ('minimum_order_qty', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product1')),
            ],
            options={
                'verbose_name': 'Available Size',
                'verbose_name_plural': 'Available Sizes',
                'ordering': ('sale_price',),
            },
        ),
    ]
