# Generated by Django 4.2.5 on 2023-10-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_tag_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
