# Generated by Django 4.2.5 on 2023-10-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_avilablesize_size_avilableamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='products_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_tag', to='products.product_tag'),
        ),
    ]
