# Generated by Django 4.2.5 on 2023-11-16 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='price',
        ),
    ]
