# Generated by Django 4.2.5 on 2023-10-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product1_products_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product1',
            name='sale_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
