# Generated by Django 4.2.5 on 2023-10-25 11:54

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_delete_cor_remove_product_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'TestCategories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='cor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.category')),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'TestSubCategories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', tinymce.models.HTMLField()),
                ('image', models.ImageField(upload_to='Whoesale/products')),
                ('SubCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategory', to='products.subcategory')),
            ],
            options={
                'verbose_name': 'products ',
                'verbose_name_plural': 'Testproductold',
                'ordering': ('id',),
            },
        ),
    ]
