# Generated by Django 4.2.5 on 2023-11-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offercount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_end_date', models.DateField(blank=True, null=True)),
                ('availability_sold', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_available', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_progress', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Offer Count',
                'verbose_name_plural': 'Offer Count',
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='product1',
            name='sale_end_date',
        ),
        migrations.DeleteModel(
            name='AvilableAmount',
        ),
        migrations.AddField(
            model_name='offercount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product1'),
        ),
    ]
