# Generated by Django 4.2.5 on 2023-11-01 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_offercount_remove_product1_sale_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability_sold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_sold', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_available', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_progress', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product1')),
            ],
            options={
                'verbose_name': 'Offer Count',
                'verbose_name_plural': 'Offer Count',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_end_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product1')),
            ],
            options={
                'verbose_name': 'Offer Count',
                'verbose_name_plural': 'Offer Count',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Offercount',
        ),
    ]
