# Generated by Django 4.2.5 on 2023-11-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product1_condition_product1_status_product1_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='sub/'),
            preserve_default=False,
        ),
    ]
