# Generated by Django 4.2.5 on 2023-11-01 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_subcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
        migrations.AddField(
            model_name='subscategory',
            name='image',
            field=models.ImageField(default=1, upload_to='sub/'),
            preserve_default=False,
        ),
    ]
