# Generated by Django 4.2.5 on 2023-11-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_subcategory_image_subscategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorys',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
