# Generated by Django 4.2.5 on 2023-11-06 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_categorys_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avilablesize',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
    ]
