# Generated by Django 4.2.5 on 2023-11-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_avilablesize_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tag',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
