# Generated by Django 4.2.5 on 2023-11-06 09:44

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_product_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='point',
            field=tinymce.models.HTMLField(),
        ),
    ]
