# Generated by Django 4.2.5 on 2023-11-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productfeature_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfeature',
            name='point',
            field=models.TextField(max_length=500),
        ),
    ]
